import { ROOT_ID } from './db'
import type { LifeArea, LoopNode } from './types'
import { makeNode } from '@/lib/nodes'
import { decompose } from '@/lib/decompose'

interface Spec {
  title: string
  area?: LifeArea
  isArea?: boolean
  minutes?: number
  weight?: 1 | 2 | 3 | 4 | 5
  energy?: 10 | 30 | 60 | 100
  children?: Spec[]
}

/** The five worlds. Always present so the map is never an empty page. */
export const WORLDS: Spec[] = [
  { title: 'Hjem', area: 'home', isArea: true },
  { title: 'Arbejde', area: 'work', isArea: true },
  { title: 'Familie', area: 'family', isArea: true },
  { title: 'Mig', area: 'personal', isArea: true },
  { title: 'Økonomi', area: 'money', isArea: true },
  { title: 'Løst og fast', area: 'other', isArea: true },
]

/** Demo content used on dev builds and behind a settings switch. */
const DEMO: Record<string, Spec[]> = {
  Hjem: [
    {
      title: 'Køkken',
      area: 'home',
      isArea: true,
      children: [
        { title: 'Tøm opvaskemaskine', minutes: 5, weight: 1, energy: 30 },
        { title: 'Køb vaskemiddel', minutes: 15, weight: 1, energy: 30 },
      ],
    },
    { title: 'Vasketøj', area: 'home', isArea: true, children: [{ title: 'Sæt en maskine over', minutes: 4, weight: 1, energy: 10 }] },
    { title: 'Rengøring', area: 'home', isArea: true, children: [{ title: 'Støvsug stuen', minutes: 15, weight: 2, energy: 30 }] },
  ],
  Arbejde: [
    {
      title: 'SOME',
      area: 'work',
      isArea: true,
      children: [
        { title: 'Instagram', area: 'work', isArea: true, children: [{ title: 'Post opslag', minutes: 20, weight: 2, energy: 60 }] },
        {
          title: 'TikTok',
          area: 'work',
          isArea: true,
          children: [
            { title: 'Find idé', minutes: 10, weight: 2, energy: 60 },
            { title: 'Filme', minutes: 25, weight: 3, energy: 60 },
            { title: 'Poste', minutes: 5, weight: 1, energy: 30 },
          ],
        },
        { title: 'Contentplan', minutes: 30, weight: 3, energy: 100 },
      ],
    },
    {
      title: 'Administration',
      area: 'admin',
      isArea: true,
      children: [{ title: 'Send faktura', minutes: 10, weight: 2, energy: 60 }],
    },
    { title: 'Kunder', area: 'work', isArea: true, children: [{ title: 'Svar på mail fra kunde', minutes: 10, weight: 2, energy: 60 }] },
  ],
  Familie: [{ title: 'Ring til mor', minutes: 15, weight: 2, energy: 60 }],
  Mig: [
    { title: 'Tandlæge', area: 'health', isArea: true, children: [{ title: 'Bestil tandlægetid', minutes: 5, weight: 2, energy: 60 }] },
    { title: 'Aftaler', area: 'personal', isArea: true, children: [{ title: 'Book frisør', minutes: 5, weight: 1, energy: 30 }] },
  ],
  Økonomi: [{ title: 'Regninger', area: 'money', isArea: true, children: [{ title: 'Betal elregning', minutes: 8, weight: 2, energy: 60 }] }],
}

interface BuildResult {
  nodes: LoopNode[]
  byPath: Record<string, string>
}

function build(specs: Spec[], parentId: string, prefix: string, demo: boolean, out: BuildResult): void {
  for (const spec of specs) {
    const breakdown = spec.children?.length ? null : decompose(spec.title)
    const node = makeNode({
      title: spec.title,
      parentId,
      area: spec.area ?? 'other',
      isArea: spec.isArea,
      estimatedMinutes: spec.minutes ?? (spec.isArea ? 0 : 10),
      mentalWeight: spec.weight ?? (spec.isArea ? 1 : 2),
      energyRequired: spec.energy ?? 30,
      steps: breakdown?.steps,
      demo,
    })
    if (breakdown) node.stepsAutoGenerated = true
    if (breakdown?.goodEnough) node.goodEnoughNote = breakdown.goodEnough
    out.nodes.push(node)
    out.byPath[`${prefix}/${spec.title}`] = node.id

    const parent = out.nodes.find((n) => n.id === parentId)
    if (parent) parent.childIds.push(node.id)

    if (spec.children?.length) build(spec.children, node.id, `${prefix}/${spec.title}`, demo, out)
  }
}

export function rootNode(): LoopNode {
  const root = makeNode({ id: ROOT_ID, title: 'Mit liv', parentId: null, isArea: true })
  root.mentalWeight = 1
  root.estimatedMinutes = 0
  return root
}

/** Creates the root plus the six worlds. Runs once, on first launch. */
export function buildBaseTree(): LoopNode[] {
  const root = rootNode()
  const out: BuildResult = { nodes: [root], byPath: {} }
  build(WORLDS, root.id, '', false, out)
  return out.nodes
}

/**
 * Demo content hung under the existing worlds. Returns only the NEW nodes plus
 * the world nodes it mutated, so the caller can persist both.
 */
export function buildDemoTree(existing: LoopNode[]): LoopNode[] {
  const out: BuildResult = { nodes: [...existing], byPath: {} }
  for (const [worldTitle, specs] of Object.entries(DEMO)) {
    const world = existing.find((n) => n.title === worldTitle && n.parentId === ROOT_ID)
    if (!world) continue
    build(specs, world.id, `/${worldTitle}`, true, out)
  }
  return out.nodes
}
