/**
 * Loops data model.
 *
 * Everything the user sees is a node in one tree. A "circle" in the UI and a
 * "task" in the data are the same object — a leaf is a task, a node with
 * children is a project, and the root is their life. That is what makes the
 * nesting arbitrarily deep without any special cases.
 */

export type NodeStatus =
  | 'open' // still costs mental load
  | 'active' // started, in progress
  | 'done' // closed loop, completed
  | 'parked' // deliberately out of mind until parkedUntil
  | 'dropped' // "this is actually not important" — also a closed loop
  | 'delegated' // handed to someone else

/** How much brain the thing takes up, not how urgent it is. */
export type MentalWeight = 1 | 2 | 3 | 4 | 5

/** Roughly how much fuel is needed to start it. */
export type EnergyLevel = 10 | 30 | 60 | 100

export type Urgency = 'none' | 'soon' | 'today' | 'overdue'

export type LifeArea = 'work' | 'home' | 'personal' | 'family' | 'money' | 'health' | 'admin' | 'other'

export interface LoopNode {
  id: string
  title: string
  description?: string
  /** null only for the single root node. */
  parentId: string | null
  childIds: string[]
  status: NodeStatus
  createdAt: number
  updatedAt: number
  completedAt?: number
  startedAt?: number
  parkedUntil?: number
  /**
   * A real time, when one genuinely exists. Loops never demands one — most
   * loops have no deadline, and inventing deadlines is how a calm system turns
   * into the stressful calendar she already refuses to use.
   */
  dueAt?: number
  /**
   * 'deadline'    — must be finished by dueAt (an application, a bill).
   * 'appointment' — happens at dueAt whether or not you did anything (a
   *                 doctor's appointment, an exam). These are never suggested
   *                 as "do this now"; you show up.
   */
  dueKind?: 'deadline' | 'appointment'
  /** Set when dueAt carries a clock time, not just a date. */
  dueHasTime?: boolean
  estimatedMinutes: number
  mentalWeight: MentalWeight
  energyRequired: EnergyLevel
  /** Grows each time the task is skipped or postponed. Used to offer help, never to scold. */
  frictionScore: number
  avoidanceCount: number
  urgency: Urgency
  /** Link into the circular time view: 'YYYY-MM-DD' + part of day. */
  scheduledDate?: string
  scheduledPart?: TimePart
  tags: string[]
  area: LifeArea
  rewardXP: number
  /** Ordered micro-steps revealed progressively in Start Mode. */
  steps: MicroStep[]
  /** True when the node is one of the app's own worlds (Hjem, Arbejde, ...). */
  isArea?: boolean
  /** Set when auto-decomposition proposed the steps, so we can tell them apart. */
  stepsAutoGenerated?: boolean
  /** Marks a node created by the seed so it can be cleared without touching real data. */
  demo?: boolean
  color?: string
  /** "Godt nok" target — completing at this level counts as a win. */
  goodEnoughNote?: string
  /**
   * What the user said is actually in the way, when the coach asked.
   * Named by her, never inferred — the point of asking is that the app should
   * not guess why a person is stuck.
   */
  blockReason?: ProcrastinationReason
  /** When the coach last raised this task, so it does not nag. */
  lastAskedAt?: number
  /**
   * What closing this is worth in kroner, if she says so. Never guessed — the
   * app has no way of knowing what a piece of work pays, and inventing a
   * number would make every statistic built on it a lie.
   */
  valueDKK?: number
}

export interface MicroStep {
  id: string
  title: string
  done: boolean
  /** The very first physical action — used by Start Mode's "just do this" screen. */
  physical?: boolean
  /**
   * Steps that ask her to write something down need somewhere to write it.
   * "Skriv de 3 vigtigste ting på listen" with only a checkbox is a step you
   * cannot actually do inside the app — she has to go find another surface,
   * which is exactly the friction this app exists to remove.
   */
  captureLabel?: string
  captured?: string
}

export type TimePart = 'morning' | 'midday' | 'afternoon' | 'evening'

/**
 * Something she wrote down that is not a task — context, a worry, a fact worth
 * keeping. Notes never enter the loop tree, so they never add mental load and
 * never show up as something to start.
 */
export interface Note {
  id: string
  text: string
  createdAt: number
  /** The loop this was written alongside, when there was one. */
  nodeId?: string
}

export interface BrainDumpEntry {
  id: string
  raw: string
  createdAt: number
  /** Node ids created from this dump, so a dump can be undone as a unit. */
  createdNodeIds: string[]
  processed: boolean
}

export type CoachRole = 'user' | 'coach'

export interface CoachMessage {
  id: string
  sessionId: string
  role: CoachRole
  text: string
  createdAt: number
  /** Quick-reply chips attached to a coach message. */
  options?: string[]
  /** Which strategy produced this line — used to avoid repeating one. */
  strategy?: string
}

export interface CoachSession {
  id: string
  startedAt: number
  endedAt?: number
  taskId?: string
  outcome?: 'started' | 'completed' | 'parked' | 'abandoned' | 'open'
  /** A short human title so she can find the conversation again. */
  title: string
  updatedAt: number
  messageCount: number
}

/**
 * Something the coach worked out and should not forget.
 *
 * Kept separate from the conversation so it survives long after the messages
 * scroll away, and so it can be shown to her — a pattern she cannot see
 * herself is only useful if she is told about it.
 */
export interface CoachMemory {
  id: string
  kind: 'pattern' | 'preference' | 'fact' | 'win'
  text: string
  /** What the observation is based on, so it is never a bare assertion. */
  evidence?: string
  createdAt: number
  /** How many times the app has seen this hold. */
  strength: number
  /** She can tell the coach it is wrong. */
  dismissed?: boolean
}

export interface Completion {
  id: string
  nodeId: string
  title: string
  completedAt: number
  /** 'done' | 'dropped' — both close a loop. */
  kind: 'done' | 'dropped' | 'delegated'
  xp: number
  /** How the loop got closed, for the friction model. */
  via: 'manual' | 'start-mode' | 'body-double' | 'what-now' | 'coach'
  minutes?: number
  /**
   * How long it actually took, when we can know (start mode to completion,
   * same sitting). This is what teaches the app to stop lying about time.
   */
  actualMinutes?: number
  /** Copied at completion time so statistics survive the task being deleted. */
  area?: LifeArea
  wasAvoided?: boolean
  valueDKK?: number
}

export type RewardKind =
  | 'loop-closed'
  | 'task-started'
  | 'brain-dump'
  | 'procrastination-broken'
  | 'return-after-break'
  | 'good-enough'
  | 'avoided-task'
  | 'daily-first'
  | 'decision-made'

export interface RewardEvent {
  id: string
  kind: RewardKind
  xp: number
  label: string
  createdAt: number
  nodeId?: string
}

export type ProcrastinationReason =
  | 'dont-know-where-to-start'
  | 'boring'
  | 'too-many-steps'
  | 'forget'
  | 'no-energy'
  | 'perfectionism'

export type ListReaction = 'love' | 'shutdown' | 'ignore'
export type EnergyPeak = 'morning' | 'midday' | 'evening' | 'varies'
export type Motivator = 'progress' | 'rewards' | 'cheering' | 'self-competition' | 'quiet-head'
export type ToneChoice = 'calm' | 'warm' | 'blunt' | 'humor' | 'peptalk'
export type InfoDensity = 'minimal' | 'balanced' | 'detailed'

/**
 * What she has told the app about herself. Never inferred, never guessed —
 * the coach speaks from this, so a wrong entry here would make it speak
 * confidently about the wrong person.
 */
export interface SelfDescription {
  /** Diagnoses she has chosen to write down, in her own words. */
  diagnoses: string[]
  /** Other things she struggles with, in her own words. */
  challenges: string[]
  /** Anything else she wants the coach to know. */
  freeText?: string
  /** How much she already knows — changes how basic the coach is allowed to be. */
  familiarity: 'new' | 'some' | 'expert'
}

export interface UserProfile {
  id: 'me'
  createdAt: number
  onboarded: boolean
  name?: string
  self?: SelfDescription
  procrastinationReasons: ProcrastinationReason[]
  listReaction: ListReaction
  energyPeak: EnergyPeak
  motivators: Motivator[]
  tone: ToneChoice
  /** Derived label, e.g. "The Momentum Brain". */
  brainProfileId: string
  /** Derived defaults the rest of the app reads. */
  density: InfoDensity
  defaultTaskMinutes: number
  autoBreakdown: boolean
  theme: 'warm' | 'dawn' | 'fog' | 'dusk'
}

export interface UserPreferences {
  id: 'prefs'
  reducedStimulation: boolean
  haptics: boolean
  goodEnoughMode: boolean
  showXP: boolean
  celebrationLevel: 'quiet' | 'normal'
  /** Saving-up-for-a-gift-card goal, entirely user-run. */
  rewardGoal?: RewardGoal
  lastOpenedAt: number
  /** Consecutive days with at least one closed loop. Never punished. */
  streak: number
  streakUpdatedAt?: string
  totalXP: number
  spentXP: number
  currentEnergy: EnergyLevel
  energySetAt: number
  /** Dictation is opt-out; it is the one feature that leaves the phone. */
  voiceEnabled?: boolean
  voiceNoticeSeen?: boolean
  /**
   * The day she has declared finished — either by reaching a small daily
   * goal, or by simply saying so. Stored as 'YYYY-MM-DD'.
   */
  doneForDay?: string
  /**
   * Extra loops she has asked for beyond today's goal. Asking for one more
   * raises the bar by one rather than clearing the day, so "nok" stays a real
   * number instead of something that silently resets.
   */
  extraToday?: number
  extraTodayDate?: string
  /** Mental load at the first opening of the day, for "det faldt X%". */
  loadSnapshot?: number
  loadSnapshotDate?: string
}

export interface RewardGoal {
  /** Store key from lib/giftcards.ts */
  storeId: string
  amountDKK: 50 | 100 | 200
  /** XP needed. Derived from amount at the time the goal was set. */
  xpTarget: number
  startedAt: number
  claimedAt?: number
}

export interface ClaimedReward {
  id: string
  storeId: string
  amountDKK: number
  xpSpent: number
  claimedAt: number
}

/**
 * The local profile lock. There is no account and no server — this record only
 * proves that a password matches, and never stores anything that could decrypt
 * her data on its own.
 */
export interface AuthRecord {
  id: 'auth'
  name?: string
  salt: string
  iterations: number
  /** SHA-256 of the derived key, not the key. */
  verifier: string
  createdAt: number
}
