/**
 * Loops data model.
 *
 * Everything the user sees is a node in one tree. A "circle" in the UI and a
 * "task" in the data are the same object — a leaf is a task, a node with
 * children is a project, and the root is their life. That is what makes the
 * nesting arbitrarily deep without any special cases.
 */

export type NodeStatus =
  | 'open' // still costs mental load
  | 'active' // started, in progress
  | 'done' // closed loop, completed
  | 'parked' // deliberately out of mind until parkedUntil
  | 'dropped' // "this is actually not important" — also a closed loop
  | 'delegated' // handed to someone else

/** How much brain the thing takes up, not how urgent it is. */
export type MentalWeight = 1 | 2 | 3 | 4 | 5

/** Roughly how much fuel is needed to start it. */
export type EnergyLevel = 10 | 30 | 60 | 100

export type Urgency = 'none' | 'soon' | 'today' | 'overdue'

export type LifeArea = 'work' | 'home' | 'personal' | 'family' | 'money' | 'health' | 'admin' | 'other'

export interface LoopNode {
  id: string
  title: string
  description?: string
  /** null only for the single root node. */
  parentId: string | null
  childIds: string[]
  status: NodeStatus
  createdAt: number
  updatedAt: number
  completedAt?: number
  startedAt?: number
  parkedUntil?: number
  /** Optional. Loops never demands a deadline. */
  dueAt?: number
  estimatedMinutes: number
  mentalWeight: MentalWeight
  energyRequired: EnergyLevel
  /** Grows each time the task is skipped or postponed. Used to offer help, never to scold. */
  frictionScore: number
  avoidanceCount: number
  urgency: Urgency
  /** Link into the circular time view: 'YYYY-MM-DD' + part of day. */
  scheduledDate?: string
  scheduledPart?: TimePart
  tags: string[]
  area: LifeArea
  rewardXP: number
  /** Ordered micro-steps revealed progressively in Start Mode. */
  steps: MicroStep[]
  /** True when the node is one of the app's own worlds (Hjem, Arbejde, ...). */
  isArea?: boolean
  /** Set when auto-decomposition proposed the steps, so we can tell them apart. */
  stepsAutoGenerated?: boolean
  /** Marks a node created by the seed so it can be cleared without touching real data. */
  demo?: boolean
  color?: string
  /** "Godt nok" target — completing at this level counts as a win. */
  goodEnoughNote?: string
}

export interface MicroStep {
  id: string
  title: string
  done: boolean
  /** The very first physical action — used by Start Mode's "just do this" screen. */
  physical?: boolean
}

export type TimePart = 'morning' | 'midday' | 'afternoon' | 'evening'

export interface BrainDumpEntry {
  id: string
  raw: string
  createdAt: number
  /** Node ids created from this dump, so a dump can be undone as a unit. */
  createdNodeIds: string[]
  processed: boolean
}

export type CoachRole = 'user' | 'coach'

export interface CoachMessage {
  id: string
  sessionId: string
  role: CoachRole
  text: string
  createdAt: number
  /** Quick-reply chips attached to a coach message. */
  options?: string[]
  /** Which strategy produced this line — used to avoid repeating one. */
  strategy?: string
}

export interface CoachSession {
  id: string
  startedAt: number
  endedAt?: number
  taskId?: string
  outcome?: 'started' | 'completed' | 'parked' | 'abandoned' | 'open'
}

export interface Completion {
  id: string
  nodeId: string
  title: string
  completedAt: number
  /** 'done' | 'dropped' — both close a loop. */
  kind: 'done' | 'dropped' | 'delegated'
  xp: number
  /** How the loop got closed, for the friction model. */
  via: 'manual' | 'start-mode' | 'body-double' | 'what-now' | 'coach'
  minutes?: number
}

export type RewardKind =
  | 'loop-closed'
  | 'task-started'
  | 'brain-dump'
  | 'procrastination-broken'
  | 'return-after-break'
  | 'good-enough'
  | 'avoided-task'
  | 'daily-first'
  | 'decision-made'

export interface RewardEvent {
  id: string
  kind: RewardKind
  xp: number
  label: string
  createdAt: number
  nodeId?: string
}

export type ProcrastinationReason =
  | 'dont-know-where-to-start'
  | 'boring'
  | 'too-many-steps'
  | 'forget'
  | 'no-energy'
  | 'perfectionism'

export type ListReaction = 'love' | 'shutdown' | 'ignore'
export type EnergyPeak = 'morning' | 'midday' | 'evening' | 'varies'
export type Motivator = 'progress' | 'rewards' | 'cheering' | 'self-competition' | 'quiet-head'
export type ToneChoice = 'calm' | 'warm' | 'blunt' | 'humor' | 'peptalk'
export type InfoDensity = 'minimal' | 'balanced' | 'detailed'

export interface UserProfile {
  id: 'me'
  createdAt: number
  onboarded: boolean
  name?: string
  procrastinationReasons: ProcrastinationReason[]
  listReaction: ListReaction
  energyPeak: EnergyPeak
  motivators: Motivator[]
  tone: ToneChoice
  /** Derived label, e.g. "The Momentum Brain". */
  brainProfileId: string
  /** Derived defaults the rest of the app reads. */
  density: InfoDensity
  defaultTaskMinutes: number
  autoBreakdown: boolean
  theme: 'warm' | 'dawn' | 'fog' | 'dusk'
}

export interface UserPreferences {
  id: 'prefs'
  reducedStimulation: boolean
  haptics: boolean
  goodEnoughMode: boolean
  showXP: boolean
  celebrationLevel: 'quiet' | 'normal'
  /** Saving-up-for-a-gift-card goal, entirely user-run. */
  rewardGoal?: RewardGoal
  lastOpenedAt: number
  /** Consecutive days with at least one closed loop. Never punished. */
  streak: number
  streakUpdatedAt?: string
  totalXP: number
  spentXP: number
  currentEnergy: EnergyLevel
  energySetAt: number
}

export interface RewardGoal {
  /** Store key from lib/giftcards.ts */
  storeId: string
  amountDKK: 50 | 100 | 200
  /** XP needed. Derived from amount at the time the goal was set. */
  xpTarget: number
  startedAt: number
  claimedAt?: number
}

export interface ClaimedReward {
  id: string
  storeId: string
  amountDKK: number
  xpSpent: number
  claimedAt: number
}
